- clean: [
    '~',
    '~/.mutt'
]

- link:
    ~/.agignore: agignore
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.ctags: ctags
    ~/.dircolors: dircolors
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gvimrc: gvimrc
    ~/.jshintrc: jshintrc
    ~/.mailcap: mailcap
    ~/.mutt/colorscheme-jess.muttrc:
        create: true
        path: mutt/colorscheme-jess.muttrc
    ~/.muttrc: muttrc
    ~/.ncmpcpp/config:
        create: true
        path: ncmpcpp.conf
    ~/.tmux: tmux
    ~/.tmux.conf: tmux.conf
    ~/.tmux_darwin.conf: tmux_darwin.conf
    ~/.tmux_linux.conf: tmux_linux.conf
    ~/.vim: vim/
    ~/.vimperatorrc: vimperatorrc
    ~/.vimrc: vimrc
    ~/.vimrc.bundles: vimrc.bundles
    ~/.vimrc.bundleconfig: vimrc.bundleconfig
    ~/.xinitrc: xinitrc
    ~/.Xresources: Xresources

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]
